### PR TITLE
Append current dir if base_path is relative

### LINKED ISSUE #32: Invalid readme build commands after latest PR
After #31 developers following readme won't be able to run examples

```
Setting pipeline to PAUSED ...
[0917/180736.657175:ERROR:context.cc(108)] The browser_subprocess_path directory (Release/gstcefsubprocess) is not an absolute path. Defaulting to empty.
[0917/180736.657298:ERROR:context.cc(108)] The locales_dir_path directory (Release/locales) is not an absolute path. Defaulting to empty.
Error initializing: Unknown option --type=zygote
Error initializing: Unknown option --type=zygote
Error initializing: Unknown option --type=utility
Pipeline is live and does not need PREROLL ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
[0917/180736.694625:FATAL:gpu_data_manager_impl_private.cc(407)] GPU process isn't usable. Goodbye.
Error initializing: Unknown option --type=utility
[1]    299009 trace trap (core dumped)  GST_PLUGIN_PATH=Release:$GST_PLUGIN_PATH gst-launch-1.0 cefsrc  ! video/x-raw
```

### PR DESCRIPTION
**Pull request by reinismu**
Manually tested

Fix #32

### CODE REVIEW

File: gstcefsrc.cc [hunk 1]
```diff
@@ -397,6 +397,17 @@ run_cef (GstCefSrc *src)
   GST_INFO  ("Initializing CEF");
 
   gchar* base_path = get_plugin_base_path();
+
+  // If not absolute path append to current_dir
+  if (!g_path_is_absolute(base_path)) {
+    gchar* current_dir = g_get_current_dir();
```
Comment (MathieuDuponchelle) [inline gstcefsrc.cc:403]: you're missing a free for that one :)

Comment (reinismu) [reply gstcefsrc.cc:403]: Good catch. How do people even make C programs without leaking memory :D

Comment (MathieuDuponchelle) [reply gstcefsrc.cc:403]: valgrind + tests + years of suffering would be the answer
